### ISSUE TITLE
Is there a way to update this component automatically?

### ISSUE THREAD

**Issue by pikadun** [MicrosoftDocs/WSL.zh-CN#10]
I checked that there is no related update for windows update and microsoft store

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 5d720f69-aff2-38d8-f0c6-9909e94acaa2
* Version Independent ID: 9d121625-e741-6d20-f3de-201a939290b8
* Content: [更新 WSL 2 Linux 内核](https://docs.microsoft.com/zh-cn/windows/wsl/wsl2-kernel#feedback)
* Content Source: [WSL/wsl2-kernel.md](https://github.com/MicrosoftDocs/WSL.zh-cn/blob/live/WSL/wsl2-kernel.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by srvbpigh** [comment]
Hello, @pikadun
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @pikadun, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/WSL/issues/597. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
