### ISSUE TITLE
Error date time

### ISSUE THREAD

**Issue by dragon-archer** [MicrosoftDocs/WSL.zh-CN#17]
In the `wsl and wsl command` section, part of the code block is below:
```txt
PS C:\Users\sarah&gt; wsl
scooley@scooley-elmer:/mnt/c/Users/sarah$ date
Sun Mar 11 19:56:57 DST 2018
scooley@scooley-elmer:/mnt/c/Users/sarah$ exit
logout

PS C:\Users\sarah&gt; wsl date
Sun Mar 11 19:55:47 DST 2018
```
The date in the first command is later than it in the second command! Is this a mistake or the time setting is error?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: deab370f-a7a1-ed3f-89ae-22194fd8fb78
* Version Independent ID: 9f406c77-415c-80db-d596-0a7fa4ea2ba9
* Content: [管理 Linux 分发版](https://docs.microsoft.com/zh-cn/windows/wsl/wsl-config#feedback)
* Content Source: [WSL/wsl-config.md](https://github.com/MicrosoftDocs/WSL.zh-cn/blob/live/WSL/wsl-config.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by srvbpigh** [comment]
Hello, @dragon-archer
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @dragon-archer, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/WSL/issues/626. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
